import { test } from 'node:test';
import assert from 'node:assert/strict';
import PocketBase from 'pocketbase';
import { randomBytes } from 'node:crypto';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
const enabled = !!process.env.EV_TEST_POCKETBASE_URL;
test('PocketBase isolation, scoped keys, real MCP transport, and review lifecycle', { skip: !enabled }, async t => {
  const url = process.env.EV_TEST_POCKETBASE_URL;
  assert.match(url, /^http:\/\/(127\.0\.0\.1|localhost):/, 'Integration tests require an isolated localhost PocketBase');
  process.env.POCKETBASE_URL = url;
  process.env.POCKETBASE_SUPERUSER_EMAIL = process.env.EV_TEST_ADMIN_EMAIL;
  process.env.POCKETBASE_SUPERUSER_PASSWORD = process.env.EV_TEST_ADMIN_PASSWORD;
  const admin = new PocketBase(url); admin.autoCancellation(false);
  await admin.collection('_superusers').authWithPassword(process.env.EV_TEST_ADMIN_EMAIL, process.env.EV_TEST_ADMIN_PASSWORD);
  const { app } = await import('../src/server.js');
  const server = app.listen(0, '127.0.0.1');
  await new Promise(r => server.on('listening', r));
  const base = `http://127.0.0.1:${server.address().port}`;
  const password = randomBytes(24).toString('hex');
  const suffix = randomBytes(5).toString('hex');
  const users = [];
  const records = [];
  t.after(async () => {
    for (const [col,id] of records.reverse()) await admin.collection(col).delete(id).catch(()=>{});
    for (const u of users) await admin.collection('ev_users').delete(u.id).catch(()=>{});
    await new Promise(r=>server.close(r));
  });
  async function user(name, verified=true) {
    const u = await admin.collection('ev_users').create({name,email:`${name}-${suffix}@example.org`,password,passwordConfirm:password,verified});
    users.push(u); const p=new PocketBase(url);p.autoCancellation(false);const auth=await p.collection('ev_users').authWithPassword(u.email,password);return{u,p,token:auth.token};
  }
  const owner=await user('owner'), reviewer=await user('reviewer'), outsider=await user('outsider'), unverified=await user('pending',false);
  async function request(path, token, method='GET', body, extra={}) {
    const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} :{}),...extra},...(body?{body:JSON.stringify(body)}:{})});
    return {status:r.status,body:await r.json(),headers:r.headers};
  }
  await assert.rejects(()=>unverified.p.collection('ev_users').update(unverified.u.id,{verified:true}));
  const input={title:'Test independent evidence review',claim:'The pilot reached the measured target.',quote:'Measured target reached in the pilot.',sourceUrl:'https://example.org/evidence',location:'Page 2',relationship:'supports',rewardCents:2000,visibility:'public'};
  assert.equal((await request('/api/v1/jobs')).status,401);
  assert.equal((await request('/api/v1/jobs',unverified.token,'POST',input)).status,403);
  const made=await request('/api/v1/jobs',owner.token,'POST',input);
  assert.equal(made.status,201);const id=made.body.id;records.push(['ev_jobs',id]);
  assert.equal(made.body.status,'draft');assert.equal(made.body.fee.feeCents,200);
  assert.equal((await request('/api/v1/jobs',outsider.token)).body.items.some(j=>j.id===id),false);
  assert.equal((await request(`/api/v1/jobs/${id}/bundle`,outsider.token)).status,404);
  await assert.rejects(()=>owner.p.collection('ev_jobs').update(id,{status:'open'}));
  await assert.rejects(()=>owner.p.collection('ev_jobs').create({...input,owner:owner.u.id,status:'open',feeBps:1000}));
  await admin.collection('ev_jobs').update(id,{status:'open'});
  const review={verdict:'supports',reasoning:'The frozen quotation states the measured result, but only within the scope of the pilot.',quote:input.quote,location:input.location,conflictFree:true};
  assert.equal((await request(`/api/v1/jobs/${id}/reviews`,owner.token,'POST',review)).status,403);
  const submitted=await request(`/api/v1/jobs/${id}/reviews`,reviewer.token,'POST',review);
  assert.equal(submitted.status,201);records.push(['ev_reviews',submitted.body.id]);
  assert.equal((await request(`/api/v1/jobs/${id}/reviews`,reviewer.token,'POST',review)).status,400);
  const ownerBundle=await request(`/api/v1/jobs/${id}/bundle`,owner.token);
  assert.equal(ownerBundle.body.payload.reviews.length,1);
  assert.equal((await request(`/api/v1/jobs/${id}/bundle`,outsider.token)).body.payload.reviews.length,0);
  const key=await request('/api/keys',owner.token,'POST',{name:'Read-only test client',scopes:['jobs:read'],expiresDays:1});
  assert.equal(key.status,201);records.push(['ev_api_keys',key.body.id]);
  assert.equal((await request('/api/v1/jobs',key.body.token)).status,200);
  assert.equal((await request('/api/v1/jobs',key.body.token,'POST',input)).status,403);
  assert.equal((await request('/api/keys',key.body.token,'POST',{name:'Forged',scopes:['jobs:read']})).status,403);
  const listed=await request('/api/keys',owner.token);
  assert.equal('tokenHash' in listed.body.items[0],false);
  assert.equal((await request('/api/keys/'+key.body.id,outsider.token,'DELETE')).status,404);
  const client=new Client({name:'integration-test',version:'1.0.0'});
  const transport=new StreamableHTTPClientTransport(new URL(base+'/mcp'),{requestInit:{headers:{Authorization:`Bearer ${key.body.token}`}}});
  await client.connect(transport);
  const tools=await client.listTools();assert.equal(tools.tools.length,4);
  const result=await client.callTool({name:'list_review_tasks',arguments:{}});
  assert.equal(result.isError,undefined);
  const rejected=await client.callTool({name:'create_review_task',arguments:input});assert.equal(rejected.isError,true);
  await client.close();
  assert.equal((await request('/api/keys/'+key.body.id,owner.token,'DELETE')).status,200);
  assert.equal((await request('/api/v1/jobs',key.body.token)).status,401);
  const login=await request('/api/auth/login',null,'POST',{email:owner.u.email,password});
  assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly/);
  assert.equal((await request('/api/v1/jobs',null,'POST',input,{Cookie:login.headers.get('set-cookie').split(';')[0]})).status,403);
  assert.equal((await request('/api/v1/jobs',owner.token,'POST',input,{Origin:'https://untrusted.example'})).status,403);
});
